import ToastContainer from '~/components/ToastContainer';
import Footer from '~/components/globals/Footer';
import Navbar from '~/components/globals/navbar/Navbar';

import '~/styles/global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ToastContainer />
        <Navbar />
        <div className="min-h-[calc(100vh-600px)] sm:min-h-[calc(100vh-300px)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
